grain_ppg = {
    "2 Row Barley": {"Max PPG": 37, "Typical PPG": 31},
    "6 Row Barley": {"Max PPG": 35, "Typical PPG": 30},
    "Apples": {"Max PPG": 29, "Typical PPG": 26},
    "Barley (Flaked)": {"Max PPG": 32, "Typical PPG": 28},
    "Biscuit/Victory Malt": {"Max PPG": 35, "Typical PPG": 30},
    "Black Patent Malt": {"Max PPG": 25, "Typical PPG": 22},
    "Blackberries": {"Max PPG": 28, "Typical PPG": 25},
    "Blueberries": {"Max PPG": 27, "Typical PPG": 24},
    "Brown Malt": {"Max PPG": 32, "Typical PPG": 28},
    "Cherries": {"Max PPG": 29, "Typical PPG": 26},
    "Chocolate Malt": {"Max PPG": 28, "Typical PPG": 24},
    "Corn (Flaked)": {"Max PPG": 39, "Typical PPG": 33},
    "Cracked Corn": {"Max PPG": 30, "Typical PPG": None},
    "Dark Crystal (120L)": {"Max PPG": 33, "Typical PPG": 28},
    "Dextrin Malt": {"Max PPG": 32, "Typical PPG": 28},
    "Grapes": {"Max PPG": 30, "Typical PPG": 27},
    "Light Crystal (10 - 15L)": {"Max PPG": 35, "Typical PPG": 30},
    "Malto-Dextrin Powder": {"Max PPG": 40, "Typical PPG": 40},
    "Medium Crystal (60 - 75L)": {"Max PPG": 34, "Typical PPG": 29},
    "Munich Malt": {"Max PPG": 35, "Typical PPG": 30},
    "Oatmeal (Flaked)": {"Max PPG": 32, "Typical PPG": 28},
    "Pale Crystal (25 - 40L)": {"Max PPG": 34, "Typical PPG": 29},
    "Peaches": {"Max PPG": 30, "Typical PPG": 27},
    "Pears": {"Max PPG": 28, "Typical PPG": 25},
    "Plums": {"Max PPG": 28, "Typical PPG": 25},
    "Raspberries": {"Max PPG": 27, "Typical PPG": 24},
    "Rice (Flaked)": {"Max PPG": 38, "Typical PPG": 32},
    "Roast Barley": {"Max PPG": 25, "Typical PPG": 22},
    "Rye Malt": {"Max PPG": 29, "Typical PPG": 25},
    "Special B": {"Max PPG": 31, "Typical PPG": 27},
    "Strawberries": {"Max PPG": 26, "Typical PPG": 23},
    "Sugar (Corn, Cane)": {"Max PPG": 46, "Typical PPG": 46},
    "Vienna Malt": {"Max PPG": 35, "Typical PPG": 30},
    "Wheat (Flaked)": {"Max PPG": 36, "Typical PPG": 30},
    "Wheat Malt": {"Max PPG": 37, "Typical PPG": 31}
}
